DROP TABLE Rated CASCADE CONSTRAINTS;
DROP TABLE Muser CASCADE CONSTRAINTS;
DROP TABLE Acted CASCADE CONSTRAINTS;
DROP TABLE Belongs CASCADE CONSTRAINTS;
DROP TABLE Movie CASCADE CONSTRAINTS;
DROP TABLE Director CASCADE CONSTRAINTS;
DROP TABLE Actor CASCADE CONSTRAINTS;
DROP TABLE Genre CASCADE CONSTRAINTS;
